version: '3'
services:
    redis:
        image: redis
    db:
        image: postgres:9.5
        environment: 
            - POSTGRES_HOST_AUTH_METHOD=trust
    vote:
        image: eesprit/voting-app-vote
        ports: 
            - "3000:80"
        links: 
            - "redis:redis"
    result:
        image: eesprit/voting-app-result
        ports: 
            - "3001:80"
        links:
            - "db:db"
    worker:
        image: eesprit/voting-app-worker
        links:
            - "db:db"
            - "redis:redis"       